defaults:
  - agent: sac

model:
  _target_: mbrl.models.Ensemble
  ensemble_size: 7
  in_size: ???
  out_size: ???
  member_cfg: ${member_cfg}
  device: ${device}
  optim_lr: 0.0001
  optim_wd: 0.0001

member_cfg:
  _target_: mbrl.models.GaussianMLP
  device: ${model.device}
  num_layers: 4
  in_size: ${model.in_size}
  out_size: ${model.out_size}
  hid_size: 200
  use_silu: true

env: "gym___Hopper-v2"
term_fn: "hopper"

env_dataset_size: 50000
validation_ratio: 0.1
dynamics_model_batch_size: 256
initial_exploration_steps: 5750
num_epochs: 125
epoch_length: 1000
patience: 5
freq_train_dyn_model: 250
effective_model_rollouts_per_step: 400
rollout_schedule: [20, 150, 1, 1]
sac_samples_action: true
num_sac_updates_per_step: 20
increase_val_set: false

seed: 0

device: "cuda:0"

log_frequency_sac: 200
log_frequency_model: 1

num_eval_episodes: 100
save_video: false

experiment: test_exp

hydra:
  run:
    dir: ./exp/mbrl/${env}/${now:%Y.%m.%d}/${now:%H%M}_${experiment}