# @package _global_
agent:
  _target_: pytorch_sac.agent.sac.SACAgent
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later
  action_range: ??? # to be specified later
  device: ${device}
  critic_cfg: ${double_q_critic}
  actor_cfg: ${diag_gaussian_actor}
  discount: 0.99
  init_temperature: 0.1
  alpha_lr: ${overrides.sac_alpha_lr}
  alpha_betas: [0.9, 0.999]
  actor_lr: ${overrides.sac_actor_lr}
  actor_betas: [0.9, 0.999]
  actor_update_frequency: ${overrides.sac_actor_update_frequency}
  critic_lr: ${overrides.sac_critic_lr}
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: ${overrides.sac_critic_target_update_frequency}
  batch_size: 256
  learnable_temperature: true
  target_entropy: ${overrides.sac_target_entropy}

double_q_critic:
  _target_: pytorch_sac.agent.critic.DoubleQCritic
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_dim: 1024
  hidden_depth: 2

diag_gaussian_actor:
  _target_: pytorch_sac.agent.actor.DiagGaussianActor
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}
  hidden_depth: 2
  hidden_dim: 1024
  log_std_bounds: [-5, 2]